
stages:
  - Quality

type-check:
  stage: Quality
  script:
    - pnpm type-check
    - echo "-------------------------- Vérification du typage statique du code terminée --------------------------"

lint:
  stage: Quality 
  script: 
    - pnpm lint 
    - echo "-------------------------- Analyse statique du code terminée -----------------------------------------"

