stages:          
  - Installing-dependencies
 

npm-installing:
  stage: Installing-dependencies
  script: 
   - cd .. && pnpm install
   - echo "-------------------------- dependencies installed -----------------------------------------------------"

