image: node:latest

before_script:
  - npm install -g pnpm

stages:          
  - Installing-dependencies
  - Type-Checking
  - Static-Analyze
  - Build
  - Test



npm-installing:
  stage: Installing-dependencies
  script: 
   - pnpm install
   - echo "-------------------------- dependencies installed -----------------------------------------------------"


checking-type:
  stage: Type-Checking
  script:
   - pnpm vue-tsc --noEmit
   - echo "-------------------------- Vérification du typage statique du code terminée --------------------------"

lint-analyze:
  stage: Static-Analyze
  script:
    - pnpm lint 
    - echo "-------------------------- Analyse statique du code terminée -----------------------------------------"

building:
  stage: Build
  script:
    - pnpm build 
    - echo "-------------------------- Construction du "package" à déployer terminée -----------------------------"

testing:
  stage: Test
  script :
    - pnpm vitest
    - echo "-------------------------- Exécution des tests terminée ----------------------------------------------"
