stages:
  - Build
  - Quality

image: node:latest

before_script:
  - npm install -g pnpm

cache:
    untracked: true
    paths:
      - /node_modules

build:
  stage: Build
  script:
    - pnpm build 
    - echo "-------------------------- Construction du "package" à déployer terminée -----------------------------"
  artifacts:
    paths:
      - dist/

quality:
  stage: Quality
  script:
    - pnpm type-check
    - echo "-------------------------- Vérification du typage statique du code terminée --------------------------"
    - pnpm lint 
    - echo "-------------------------- Analyse statique du code terminée -----------------------------------------"
    - pnpm test --parallel
    - echo "-------------------------- Exécution des tests terminée ----------------------------------------------"
