image: node:latest

stages:          
  - Installing-dependencies
  - Type-Checking
  - Static-Analyze
  - Build
  - Test


before_script:
  - npm install -g pnpm

npm-installing:
  stage: Installing-dependencies
  cache:
    paths:
      - /node_modules
  script: 
   - pnpm install
   - echo "-------------------------- dependencies installed -----------------------------------------------------"
  


checking-type:
  stage: Type-Checking
  script:
   - pnpm type-check
   - echo "-------------------------- Vérification du typage statique du code terminée --------------------------"

lint-analyze:
  stage: Static-Analyze
  script:
    - pnpm lint 
    - echo "-------------------------- Analyse statique du code terminée -----------------------------------------"

building:
  stage: Build
  script:
    - pnpm build 
    - echo "-------------------------- Construction du "package" à déployer terminée -----------------------------"
  artifacts:
    paths:
      - build/index.html

testing:
  stage: Test
  script :
    - pnpm vitest
    - echo "-------------------------- Exécution des tests terminée ----------------------------------------------"
