stages:
  - Build
  - Quality

image: node:latest

before_script:
  - npm install -g pnpm



build:
  stage: Build
  cache:
    paths:
      - untracked: true
      - /node_modules
  script:
    - pnpm install
    - pnpm build 
    - echo "-------------------------- Construction du "package" à déployer terminée -----------------------------"
  artifacts:
    paths:
      - dist/

type-check:
  stage: Quality
  script:
    - pnpm type-check
    - echo "-------------------------- Vérification du typage statique du code terminée --------------------------"

lint:
  stage: Quality 
  script: 
    - pnpm lint 
    - echo "-------------------------- Analyse statique du code terminée -----------------------------------------"
  needs: 
    - type-check
test:
  stage: Quality
  script:
    - pnpm test 
    - echo "-------------------------- Exécution des tests terminée ----------------------------------------------"
    


