stages:
    - build
    - Quality
    - test

image: node:latest

cache: &global_cache
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store
    - node_modules/
  policy: pull

before_script:
    - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@7
    - pnpm config set store-dir .pnpm-store


include: "/pipelines/templates/quality-template.yml"
include: "/pipelines/templates/tests-template.yml"



build:
    stage: build
    cache:
        <<: *global_cache
        policy: pull-push
    script:
        - pnpm install
        - pnpm build
    artifacts:
        paths:
            - dist/
type-check:
  stage: Quality
  script:
    


lint:
  stage: Quality
  script:

run-test:
  stage: test
  script:



