name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
      
      - name: setup pnpm environment
        uses: pnpm/action-setup@v2
        with:
          version: 7.1.7
            
      - name: build
        run: |
          pnpm install
          pnpm build
          
      - name: Upload artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: vue2048
          path: dist/
          
      - name: Run Unit Tests
        if: github.event_name == 'pull_request'
        run: |
          pnpm test
          
      - name: Run Linter
        if: github.event_name == 'pull_request'
        run: |
          pnpm lint
          
      - name: Run Type Checker
        if: github.event_name == 'pull_request'
        run: |
          pnpm type-check
