name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup pnpm environement
        uses: pnpm/action-setup@v2
        with:
            version: 7.1.7
      - name: build
        run: |
          pnpm install
          pnpm build
