name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME_PROD: stapp-vue2048-prod 
  AZURE_WEBAPP_NAME_QA: stapp-vue2048-qa
  AZURE_WEBAPP_PACKAGE_PATH: './dist/'       
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
      
      - name: setup pnpm environment
        uses: pnpm/action-setup@v2
        with:
          version: 7.1.7
            
      - name: build
        run: |
          pnpm install
          pnpm build
          
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vue2048
          path: dist/
          
      - name: Run Unit Tests
        if: github.event_name == 'pull_request'
        run: |
          pnpm test
          
      - name: Run Linter
        if: github.event_name == 'pull_request'
        run: |
          pnpm lint
          
      - name: Run Type Checker
        if: github.event_name == 'pull_request'
        run: |
          pnpm type-check
          
  deploy:
       runs-on: ubuntu-latest
       needs: build
       steps:
       - name: Download artifact 
         uses: actions/download-artifact@v3
         with:
           name: vue2048
       - name: Deploy to prod 
         uses: azure/webapps-deploy@v2
         with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_PROD }}
          publish-profile: ${{ secrets.AZURE_TOKEN_PROD }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          action: 'upload'
          skip_app_build: true
         
       - name: Deploy to qa
         uses: azure/webapps-deploy@v2
         with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_QA }}
          publish-profile: ${{ secrets.AZURE_TOKEN_QA }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          action: 'upload'
          skip_app_build: true
